### ISSUE TITLE
Improve usability of the actions available once a simulation is completed

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#434]
- [ ] Design how to achieve the goals?
- [x] Stop replay of colours when simulation comes to end of data (#428)
- [x] Stop moving traces when simulation comes to end of data (#428)
- [ ] When shift/play (stream/display time evolution of graphs) is selected, a widget should be popped up showing the value of t, i.e. time at that moment. (openworm/org.geppetto#521)
- [ ] List of all variables that were recorded
- [ ] ... fill in after design

Goals:
- Easier to get on multicomp cell, even if plots there already

Ideas:

- New Button: “Results” - only enabled when results loaded - get a summary of results & number of options to plot or display on cells (related: openworm/org.geppetto#522)

- Test replay of volts on cells with lines for neurites

**Comment by pgleeson** [comment]
Related to this, probably: https://github.com/openworm/org.geppetto.frontend/issues/428

**Comment by slarson** [comment]
Also related is openworm/org.geppetto#445
